version: 2
updates:
  - package-ecosystem: npm
    directory: "/calculadora-nutricional"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      security-and-patch-updates:
        update-types:
          - patch
          - minor
